export { AppConfig } from './app'
export type { RouterConfig } from './app'
export { getRouterConfig } from './app'
export { default } from './app'
export { prefixedKey } from '@/constants/storage'
export { migrateUnprefixedKeys } from './migration'
