export { default as LayoutHeader } from './Header.vue'
export { default as LayoutSidebar } from './Sidebar/index.vue'
export { default as LayoutFooter } from './Footer.vue'
export { default as LayoutTabs } from './TagsView/index.vue'
export { default as SettingDrawer } from './SettingDrawer/index.vue'
